### ISSUE TITLE
help needed to build the web_app - compile error in Arduino Studio

### ISSUE THREAD

**Issue by knopserl** [LightJockey/EspDmxNode#1]
Hello,
I wanted to port use the great project for an ArtNet controller (I wanted to use if on an ESP32).
I get a compile error in web.h as it does not find a web_app .h file.
Compilation error: web_app/dist/index.html.gz.h: No such file or directory.

Since I'm not a Web or JavaScript expert, I assume that the file need to be created with something in the web_app build directory?
It .js file cant be executed. So I need some help here.

**Comment by LightJockey** [comment]
Hello,

I looked into adding basic ESP32 support but unfortunately it looks like the ArtNet library I'm using has been abandoned, so this will remain only compatible with 8266 boards for the foreseeable future.
Sorry about the misleading info about the ESP32 compatibility, I will update the README to reflect this.

Keep in mind this is quite the old project though, and while it still works great on the 8266s I got, WLED in the meantime has become THE firmware for anything addressable pixels / DMX nodes. Is there any reason you looked into this one first? As far as I'm aware the only thing WLED lacks is frame interpolation (smoothing), but makes up with many more features. Please go check that one out if you still haven't :)

**Comment by knopserl** [comment]
Hi LightJockey,
I actually like your project as it does mostly what I need. I also like your web UI very much and MQTT support.
I need an ArtNet node with Wifi (I will try to add Ethernet support as I want it to connect to a switch) and control a set of moving heads. 
I have an ArtNet (Ethernet -> DMX) adapter, but I want to extend it with some additional features (Bluetooth ...).

The only problem I have is to build your Web Interface. I have no clue how this works in Arduino Studio and I have also tried it in Visual Studio Code. There is a build for the web_app, but it throws a lot of errors like:

Cannot find module 'chalk' ...
after some hours I came further and ran into next problems e.g. that the used module require('extract-text-webpack-plugin') is depreciated.

Could you give me some hints how to build the Web UI (web_app) or do the build for me and upload the index.gz and .gz.h file, so that either Arduino Studio or VS Code succeed.

How to upload the web_app? (usually web code is in a data directory and can be uploaded with Arduino).

Are you really abandon this nice ESP project? 

nice greetings from Austria
Heinz

**Comment by LightJockey** [comment]
Thank you for your interest but unfortunately building the web app alone is not enough to successfully build for ESP32, other build errors will pop up after that which involve the ArtNet and DMX library the project is using.
That library is indeed quite old and might be better replaced for a modern alternative, which I might be doing in the future.

For the time being I'm afraid you'll have to get your hands on an ESP8266 if you really wish to use this project, which honestly is more than enough to run a single DMX universe, those tiny boards still rock :)

I updated the readme with instructions and a precompiled firmware binary if you want to try it out.

Compiling the web interface should now be done automatically on build with PlatformIO (again, check the readme), but can be triggered manually by running `npm run build` inside the src/web_app folder, as you've already discovered yourself.
It spits out a bunch of deprecated warnings but it should work, it does for me at least.
Try it with the whole project open within VSCode, you don't have to use Arduino Studio as the PlatformIO extension of VSCode is a replacement of that, and this project is setup to be compiled within that environment.
But then again, all of the above doesn't apply unless you're interested in building from source for an ESP8266.

Hope this helps!

**Comment by knopserl** [comment]
thanks a lot for your quick response.
I'm fine with the ESP8266 board (I have all kind of NodeMCU's as well as all kind of ESP32). I'm not yet focusing on the ESP32 port. I think I can manage that later and see no big problems.
What worries me more is, that I cant build the web_app in VS Code. I'm not just getting warnings but fatal errors.

web_app build:
Error: Cannot find module 'chalk'
...
then as a consequence in the EspDmxNode build
src\web.h:8:40: fatal error: web_app/dist/index.html.gz.h: No such file or directory

So I'm not able to build the web_app and that is the one, I'm the least expert and tried around a lot to get rid of the errors beginning with the chalk and the I ended up with the extract-text-webpack-plugin which is no longer supported and when is use the recommended replacement mini-css-extract-plugin, some methods in the other source are not found (it's not a 1:1 replacement).

When I use the original source of web_app and install the module chalk and the restart the compile, I get another error:
> spa@1.0.0 build    
> node build/build.js

- building for production...node:fs:581
  return binding.open(
                 ^
Error: ENOENT: no such file or directory, open 'D:\mcdev\vscode\_projects\EspDmxNode\src\web_app\dist\index.html.gz'

But the web_app is one of the part I like most (not the only one).
Maybe you can provide me just the compiled/zipped web_app? Or any hints how to get the source compiled?
I'm using all latest VS Code, PlatformIO, node/nodejs, npm etc. etc.

**Comment by LightJockey** [comment]
Apologies, my dumb ass forgot all sorts of things and it was indeed very broken.
I pushed a fix, can you tell me if it works now?

**Comment by knopserl** [comment]
> Apologies, my dumb ass forgot all sorts of things and it was indeed very broken. I pushed a fix, can you tell me if it works now?

Thanks a lot. The build now succeeded!
No I can work on the ESP32 port and support for Ethernet (not WiFi) as I wanted the adapter to be connected to a LAN switch.
The most important part (I'm not an expert at all) was the web part, which I like.
I also will reuse the ArtNEt and DMX part of your code but need to use the latest ArtNet (Ethenet) + DMX libraries and here the ESP32 supported ones.
thanks and greetings from Austria!

**Comment by LightJockey** [comment]
Glad to hear that :)
Feel free to reach out if you need more help

**Comment by MicroMarty** [comment]
Beautiful work indeed!

@knopserl Maybe you know this project, but just in case, here is [the link](https://github.com/expanseElectronics/ethernetNodes) .
It's an esp8266 Ethernet Artnet node, I had some success with it, but presently I don't succeed in keeping it stable.
Tell me if you manage to make it run clean.
