### ISSUE TITLE
src\web.h:8:40: fatal error: web_app/dist/index.html.gz.h: No such file or directory

### ISSUE THREAD

**Issue by larry24370** [LightJockey/EspDmxNode#4]
hello, get that error : src\web.h:8:40: fatal error: web_app/dist/index.html.gz.h: No such file or directory

**Comment by LightJockey** [comment]
Hi, can you please try running the command `npm run build` inside the `src/web_app` folder?

**Comment by larry24370** [comment]
hi, tks a lot for your reply, your help, and your wonderful job. I'm pretty
newbie.. so i'm trying... i have to do a new folder with your data and test
agin from the beginning, only installed visual studio, platformio , opened
your folder and do the step you said on your github.

Le jeu. 7 mars 2024 à 19:20, LightJockey ***@***.***> a
écrit :

**Comment by LightJockey** [comment]
No problem, I'm glad to help.
Make sure you also have node.js and python installed, it should work after that.
If not, send me the whole terminal output when you try to build the project

**Comment by larry24370** [comment]
ok i think that is the issue node.js and python.. so i install them now.
Big tks

Le jeu. 7 mars 2024 à 19:57, LightJockey ***@***.***> a
écrit :

**Comment by LightJockey** [comment]
Alright, let me know how it goes!

**Comment by larry24370** [comment]
It working... tks again

Le jeu. 7 mars 2024 à 20:29, LightJockey ***@***.***> a
écrit :
