### ISSUE TITLE
Wifi issue

### ISSUE THREAD

**Issue by larry24370** [LightJockey/EspDmxNode#5]
Hello can you modify the code? My mean is : if we insert bad password wifi or the router is bad, we lose connection to the node and so can not use again instead of flashing it again? Could add a function exemple if can not connect to the router with password/ssid we insert, could return to AP mode? and we can adjust that delay into web app? No data provide = AP, if data provide = Normal mode (connect to the router) but if router connection fail after a delay, go back to AP mode, so we can modify what is wrong or change ssid/password for new router... Thanks a lot

**Comment by larry24370** [comment]
maybe also it can scan for available SSID network? then instead of enter manually SSID, we select it?

**Comment by LightJockey** [comment]
Yeah those edge cases can definitely be handled better, I will look into that soon.

> maybe also it can scan for available SSID network? then instead of enter manually SSID, we select it?

I'll probably put this one in alongside some badly needed UI tweaks, thank you for the suggestion

**Comment by larry24370** [comment]
Glad to help!  i just checked many similar project and collect best
features from all.... also many can switch to send/receiver, it is also a
great feature... thanks, and take care.

Le mar. 12 mars 2024 à 12:48, LightJockey ***@***.***> a
écrit :
